version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
       - ./data:/var/lib/postgresql/data 
    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL:  admin@email.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    volumes:
       - ./pgadmin:/root/.pgadmin
    ports:
      - 5434:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge